- hosts:
    - all
    - localhost
  become: yes
  tasks:
    - name: include vars from ../vars.yml
      include_vars:
        file: ../vars.yml

- hosts:
    - all
    - localhost
  roles:
    - aeimer.install_bat
  tasks:
    # Install duf for inspecting  from https://github.com/muesli/duf
    - name: Check if duf is installed
      command: dpkg-query -W duf
      register: duf_check_deb
      failed_when: duf_check_deb.rc > 1
      changed_when: duf_check_deb.rc == 1
    - name: Download duf
      get_url: 
        url="https://github.com/muesli/duf/releases/download/v{{ duf_version }}/duf_{{ duf_version }}_linux_amd64.deb"
        dest="/tmp/duff.deb"
      when: duf_check_deb.rc == 1
    - name: "Install duf package for inspecting disk usage"
      become: yes
      apt: deb="/tmp/duff.deb"
      when: duf_check_deb.rc == 1
    - name: Install tools
      apt:
        pkg:
          - tree
          - neofetch
          - fd-find # https://github.com/sharkdp/fd

    # Install exa for ls replacement  https://the.exa.website/#installation
    - name: Check if exa is installed
      command: which exa
      register: check_exa
      failed_when: check_exa.rc > 1
      changed_when: check_exa.rc == 1
    - name: Download exa
      get_url: 
        url: "https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip"
        dest: "/tmp/exa.zip"
      when: check_exa.rc == 1
    - name: "Install exa"
      ansible.builtin.unarchive:
        src: /tmp/exa.zip
        dest: /tmp
      when: check_exa.rc == 1
    - name: Copy exa to usr bin
      become: yes
      copy: 
        src: /tmp/exa-linux-x86_64
        dest: /usr/bin/exa
      when: check_exa.rc == 1
    - name: "Give exa +x perm"
      when: check_exa.rc == 1
      become: yes
      ansible.builtin.shell: 
        cmd: "chmod +x /usr/bin/exa"

    # Install procs https://github.com/dalance/procs
    - name: Check if procs is installed
      command: which procs
      register: check_procs
      failed_when: check_procs.rc > 1
      changed_when: check_procs.rc == 1
    - name: Download procs
      get_url: 
        url: "https://github.com/dalance/procs/releases/download/v0.11.3/procs-v0.11.3-x86_64-lnx.zip"
        dest: "/tmp/procs.zip"
      when: check_procs.rc == 1
    - name: "Install procs"
      become: yes
      ansible.builtin.unarchive:
        src: /tmp/procs.zip
        dest: /usr/bin/
      when: check_procs.rc == 1